---
- hosts: all
  gather_facts: yes
  become: yes
  name: Upgrade software
  tasks:
    # Use a block to perform tasks conditionally—only if running Ubuntu 20.04.
    - block:
      - name: Install cephadm (defaults to Octopus)
        apt:
          name: cephadm
          state: present

      - name: Install gnupg
        apt:
          name: gnupg
          state: present

      - name: Update ceph repo to Pacific
        shell: "cephadm add-repo --release pacific"

      - name: Update ceph repo to Pacific
        shell: "rm /etc/apt/trusted.gpg.d/ceph.release.gpg"

      - name: Download ceph apt signing key
        get_url:
          url: https://download.ceph.com/keys/release.asc
          dest: /tmp/release.asc

      - name: Install ceph apt signing key
        shell: "apt-key add /tmp/release.asc"

      - name: Update cephadm to Pacific
        apt:
          name: cephadm
          state: latest
          update_cache: yes
          force: yes

      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'
