---
- hosts: all
  serial: 1
  gather_facts: yes
  become: yes
  name: Upgrade Ubuntu to 20.04
  vars:
    health_osd_check_retries: 40
    health_osd_check_delay: 30
    mon_group_name: "mons"
    cluster: "ceph"
    reboot_required_path: "/var/run/reboot-required"
  tasks:
    # Use a block to perform tasks conditionally—only if running Ubuntu 18.04.
    - block:

      - assert:
          that: ansible_version.full >= "2.8.0"

      - debug:
          msg: 'This server is running Ubuntu 18.04 LTS and all packages will be upgraded.'

      # Now would be a good time to take a backup if you can trigger an
      # automated backup!

      - name: Remove the EOL message of the day if one exists.
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - /etc/update-motd.d/99-esm
          - /run/motd.dynamic

      - name: Update ceph repo preferences
        copy:
          src: ../files/ceph.pref
          dest: /etc/apt/preferences.d/ceph.pref

      - name: Set grub to continue booting after unclean shutdown
        lineinfile:
          path: /etc/default/grub
          regexp: "^GRUB_RECORDFAIL_TIMEOUT"
          line: "GRUB_RECORDFAIL_TIMEOUT=0"

      - name: Apt upgrade all packages to the latest version
        apt: update_cache=yes upgrade=full

      - name: Reboot node
        import_tasks: ../common-tasks/ceph_rolling_reboot.yml

      - name: Apt dist upgrade
        apt: update_cache=no upgrade=dist

      - name: Reboot node
        import_tasks: ../common-tasks/ceph_rolling_reboot.yml

      - name: Ensure update-manager-core is installed.
        apt: name=update-manager-core state=present

      - name: Enable Ubuntu LTS upgrades
        replace:
          path: /etc/update-manager/release-upgrades
          regexp: "^(Prompt=.+)$"
          replace: "Prompt=lts"

      - name: Copy upgrade script to target
        copy:
          src: ../files/upgrade_ubuntu_to_focal/run_upgrade.sh
          dest: /var/tmp/run_upgrade.sh

      - name: Upgrade log reminder
        debug:
          msg:
          - 'A log of the upgrade can be found on the node at /var/log/release-upgrade_$( date +%F ).log'

      - name: Run upgrade script with do-release-upgrade non-interactively.
        command: bash /var/tmp/run_upgrade.sh

      - name: Reboot node
        import_tasks: ../common-tasks/ceph_rolling_reboot.yml

      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

    - name: Update node facts
      setup:

    - name: Node upgrade status
      debug:
        msg:
        - "OS release: {{ ansible_lsb['release'] }}"
        - "Kernel: {{ ansible_kernel }}"
        - "Uptime: {{ ansible_uptime_seconds }} seconds"

    - name: Pause before upgrading next node
      pause:
        prompt: "Hit enter to begin upgrading the next node"
        echo: yes

